### ISSUE TITLE
Galacticraft/More Planets Ticking Memory Connections@Thermometer 

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#82] opened 2016-01-20 22:49 UTC
Version: beta12b
Crash Report: http://pastebin.com/JVkGtysJ

Galacticraft and More planets both crash with the season mod if you go to one of there planets/dimensions and right click with the seasons thermometer. It has a ticking memory connection

**Comment by TheWeatherPony** [comment] 2016-01-20 22:59
Same basic cause as #80.

**Comment by TheWeatherPony** [comment] 2016-01-23 05:11
Taking another look, this is actually a duplicate of another in #80 (Galacticraft/More Planets)

**Closed as completed by TheWeatherPony** 2016-01-23 05:11 UTC
