### ISSUE TITLE
[EnhanceMent] Tabbing Preventing Easy Access

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#34] opened 2015-10-24 03:23 UTC
version: beta8b,beta8a,beta8c3,beta8c4
Image: http://imgur.com/eFtCV97
Priority: Very Low
upon pressing tab /seasons set season (tab) it starts to say autumn then new and you pres tab it changes the season and adds another new. For example:
1. /seasons set season (tab)= /seasons set season Autumn
2. /seasons set season Autumn (tab)= /seasons set season New World
3. /seasons set season New Spring (tab)= /seasons set season New Summer
4. /seasons set season New Summer (tab)= /seasons set season New Winter 
5. /seasons set season New Winter (tab)= /seasons set season New Autumn
6.   /seasons set season New Autumn (tab)= /seasons set season New Autumn
7. /seasons set season New Autumn (tab)= /seasons set season New New World
8. The process repeats over and over again with you tabbing it.

What This Prevents:

I can't tab (Summer or Spring) without /seasons set season s
I can't tab (Winter without) /seasons set season w
If you could fix this when you have time it would be appreciated.

**Comment by jredfox** [comment] 2015-10-24 03:24
AAAAAAAAAAAAAAh I just closed it by accident. Ok it's all good

**Comment by TheWeatherPony** [comment] 2015-10-24 05:34
The "New" is caused by the name of your world being "New World" - the seasonal command has an optional one-word-name argument to specify another world when used in-game. The real problem behind this issue will be fixed at the same time as #4.

**Closed as completed by TheWeatherPony** 2015-10-24 05:34 UTC

**Comment by jredfox** [comment] 2015-10-24 05:44
ok then lock this to.
