### ISSUE TITLE
AoA NeverMine 2/DivineRPG Incompatibility

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#59] opened 2016-01-06 04:05 UTC
Version: beta10
Loading Loop AoANeverMine2: http://pastebin.com/9iF3p9s0
DivineRPG: http://pastebin.com/nkGYz1hD

When I went to the haven for aoa nevemine 2 with seasons loaded it seemed to load a loop as I was watching the console and it was in a constant loop ever .5 seconds. It couldn't load AoA Nevermine 2. It does the same thing to certain divine rpg dimensions. It might just do this in general with dimensional mods and dimensions.

**Comment by TheWeatherPony** [comment] 2016-01-06 09:00
The issue is that a mod is doing it's own WorldGen, so TSM cannot tell which world is "the current world" - this leads to TSM printing a little blurb about how the issue was reached... every single time that it happens. In other words, the mod is printing a stack trace 16x16 times per generated chunk. If you left the game running, it would eventually finish generating... eventually.

The only way that I can solve this kind of issue is one-at-a-time.

**Comment by jredfox** [comment] 2016-01-06 21:37
I think it might just happen randomly if the mod has enough dimensions. I think it might do this with galacticraft or any mod that has more then 2 dimensions.  I should test this.

**Comment by TheWeatherPony** [comment] 2016-01-06 22:20
"seasons: biome edits: wDat is null - side is SERVER"
The message might not be all that clear, but it's intended for me, so it doesn't need to be - I understand it. This message means that worldly settings for what the mod believes is the current world are not already loaded, cannot be loaded, and cannot be generated. The only case when this is so is when the "current world" is unidentified. By then looking at the stack trace(s), I see that there is worldgen going on; worldgen needs special handling - without that special handling, snow gets placed randomly when generating the land (a pervious bug you've reported).

**Comment by jredfox** [comment] 2016-01-07 00:07
ok well then can you add support for specific mods in the future then? Also in the meantime could you add white lists and black lists for dimensions banning seasons from those dimensions. it's already an enhancement on github

**Comment by TheWeatherPony** [comment] 2016-01-09 18:35
This particular issue should be fixed for these two mods, and several others, for the next build. If you find any others for the next build, please make a new issue for them ;)

**Closed as completed by TheWeatherPony** 2016-01-09 18:35 UTC

**Comment by jredfox** [comment] 2016-01-09 20:41
Nice. That will make this alot more popular when the release comes out now that dimensional mods should now work with the seasons mod.
