### ISSUE TITLE
Already tesselating!

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#16] opened 2015-10-22 00:15 UTC
Already tesselating!
version: beta8b and beta8c3 ? 
http://pastebin.com/MAtgT4pX

**Comment by PitchBright** [comment] 2015-10-22 01:17
Stacktrace says it's not a Seasons bug. Please close.

**Comment by TheWeatherPony** [comment] 2015-10-22 01:21
Duplicate of https://github.com/TheWeatherPony/ProjectPrivateRainbow/issues/13

**Closed as completed by TheWeatherPony** 2015-10-22 01:21 UTC
Labels: duplicate
