### ISSUE TITLE
 Exception in server tick loop beta8b

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#11] opened 2015-10-21 23:58 UTC
http://pastebin.com/KmyxNteX

**Comment by jredfox** [comment] 2015-10-22 00:03
AAAAAAAAAAAAAAAAAAAAAAAAA? I can't paste more then 10 pastebins in 24 hours without an account so there is a limit on the amount of work I can do.  Now I can only do 25 per 24 hours .

**Comment by TheWeatherPony** [comment] 2015-10-22 05:08
Duplicate of #8

**Closed as completed by TheWeatherPony** 2015-10-22 05:08 UTC
Labels: duplicate
