### ISSUE TITLE
[Enhancement] Adjust The Time That Seasons Sets The Day To The Time Before Creation of a World

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#68] opened 2016-01-11 01:44 UTC
Version: beta10
Images: http://imgur.com/a/xy18G

Seasons upon creating world sets a day then until the world ticks it remains that day. Then it jumps another day from 30 seconds-about 1 minuet. This is  caused by seasons time to set a new day is after the time of the creation of the world making it if it's day 6 autumn it would become winter (in previous working seasonal transitions).  I highly recommend adjusting time to before the world is created so it will have to tick for an entire minecraft day before it changes the seasons day. Since I don't know vanilla on what time it is from the creation of the world I cannot give examples.

**Comment by TheWeatherPony** [comment] 2016-01-11 04:21
The problem with changing it to be before the start of the world is that the time the world starts is also the time players wake up at. I wrote some code to try and support advancing the seasonal day when the player sleeps through the advancement time, but it never really worked quite right. My solution was to make it advance at some time after the player woke up and before the player would go to bed.

The time that the seasons advance at is configurable, with the settings "DayTransition_hour" and "DayTransition_minute". The hour is in military time, and players wake up at 06:00.

**Comment by jredfox** [comment] 2016-01-11 05:25
will you can add support for beds. just make it coded that seasons changes a day after you sleep through the night. make it from like the /seasons set day command and just add one. That isn't what I was talking about at all.  I was saying you spawn in a brand newly generated world and that has a certion specified time. your seasons doesn't transition till after that certain hour.  So it changes after it already sets what day it is. I was saying make it like an hour before you spawn in the world and it's the default time. As for beds make it so it /adds a day to seasons. now if it's the 6th day make it change seasons so on the 7th day when you wake up it's a brand new season. however /seasons set day 7 doesn't work and when it did it had some serious issues it didn't properly change seasons and pretty much corrupted the world so instead of doing that for the 7th make it so it changes a season like the current setup for it to change the season after a certain hour go about it that way and reset the day to 0 of the next season.

**Comment by TheWeatherPony** [comment] 2016-01-11 06:31
I _likely will_ end up just hooking into the sleep/wakeup code (I'm already doing an uncountable number of edits [due to dynamically weaving them in]... what's another one?)
- the time of day you spawn in a new world = the time of day you wake up at when you sleep in a bed.
- the mod's old seasonal advancement through sleep code doesn't work correctly, so the transition was made to be during the day, otherwise the seasons would never advance when the player(s) slept.
- setting the seasonal transition to be before the start of the world = setting the seasonal transition to be before the player wakes up after going to bed = the seasons don't advance when the player(s) sleep.

**Comment by TheWeatherPony** [comment] 2016-01-11 06:48
bug fixed: seasonal set day command doesn't actually change the season when given a day number that should be changing it.

**Comment by jredfox** [comment] 2016-01-11 21:30
well that's good for beds but, what about the seasons setting the next day after the creation of the world?

**Comment by jredfox** [comment] 2016-01-29 05:00
still isn't fixed.  
Here is a possible solution:
why don't you reset the time just an hour before the creation of the world.  Also for beds run the command or method to add a day for seasons and on the 7th day transition it and set the day to 0.

**Comment by TheWeatherPony** [comment] 2016-01-29 06:49
The problem isn't changing the seasons - it's figuring out when to change the days, which in turn changes the seasons. Vanilla sleep code is a little... interesting to work with. And this issue's not fixed, just like the issue report isn't closed...

**Comment by jredfox** [comment] 2016-01-29 21:34
ok I get it the bed code is a mess to work with because, it's hard to tie to with the time and bed at once.  hope you can get it working.

**Comment by jredfox** [comment] 2017-02-04 08:01
**I think the solution to this would be to edit the default world creation time to after the player wakes up from sleeping and after the seasonal day takes place a couple ticks. After that is edited then set the seasonal day a couple ticks after the player wakes up out of bed to the next seasonal day.** I am sure you have already done some vanilla edits in the first place to get seasons to do what it does already. I don't think this would be too much to ask for.

**Comment by TheWeatherPony** [comment] 2017-06-18 19:23
This has been addressed in the new 3.0-alpha for 1.8.9 (which has been released as an Alpha).
Instead of being able to start on the last day of a season, then changing to the next season moments after starting a world, it is now instead possible to start on the day before the first day of a season (yet it still being the upcoming season).

**Closed as completed by TheWeatherPony** 2017-06-18 19:23 UTC

**Comment by jredfox** [comment] 2017-07-16 01:50
nice
