### ISSUE TITLE
Dimension Null Point Exception  Unexpected error

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#80] opened 2016-01-20 22:29 UTC
Version: beta12
Orespawn: http://pastebin.com/YBqYEUpH
Tropicraft: http://pastebin.com/1Zvd0UVj
More Planets Fronos Planet(Dimension): http://pastebin.com/vwTDzfx3
Galacticraft Or more planets Asteroid Belt http://pastebin.com/HcvDwmce
Magic Crusade; Crash1: http://pastebin.com/f13WzujE Crash 2 http://pastebin.com/8KVLMiyL
Crash3: http://pastebin.com/8KVLMiyL  Crash4: http://pastebin.com/wehJGQdM

These are all crashes from an unexpected error which occurred without optifine. It only seemed to crash if you went into the dimension and then it would crash with that errors you see above.

**Comment by TheWeatherPony** [comment] 2016-01-20 22:59
Each of these is caused by being in/near a biome that isn't what it is.
Before beta12/beta12b was released, Biomes O Plenty had this issue as well. The problem is that a biome that isn't in the game's biome array (and therefore isn't known by TSM) tried to get it's seasonal temperature. This would almost exclusively happen when a biome is only half replaced with an alternate version.

Could you please show me each unique line containing "Seasons: failed to get biome settings for biome: ", and the list of known biomes following it, from the PML logs for each? It would help me shift through each of those mods' code and find the cause/solution.

**Comment by jredfox** [comment] 2016-01-20 23:07
ok I will try  but, doesn't forge have biome temperatures loaded or something? Couldn't you use it's data?

**Comment by TheWeatherPony** [comment] 2016-01-20 23:56
Forge doesn't do loading/saving of biome temperatures. Vanilla has a decimal number for temperature in each section of memory associated with a biome, and all loaded biomes are accessible through an array. But if a mod removes a biome and replaces it with a customized version, without fully removing the old one, that problem comes up.

**Comment by jredfox** [comment] 2016-01-23 05:45
could you try adding seasonal temperatures after it registers the temperatures rather then before and it freaking out mods. If I decided a mod like a dimension mod I would not know how to make it compatible. I will look into the pml logging like you said. I have been sick lately.

**Comment by TheWeatherPony** [comment] 2016-01-23 07:39
Temperatures gets registered at the moment the biome is originally created, and TSM doesn't check to see what the biomes are (or what their temperatures are) until after all biomes are already fully set up... although some custom biomes do some custom trickery to mask other/older ones.

No worries about being ill - I've released a public version of the mod (beta12c). That one is just the last one you worked with, but with some extra and more clear information when this temperature issue comes up.
Rest well, and I hope you feel better soon.

**Comment by TheWeatherPony** [comment] 2016-01-23 07:44
Actually, since there's new/different stuff that happens when this issue comes up, I'm going to close this issue so that it's not confusing for those that didn't try beta12b. Should still happen, but it's now a Seasons_UnknownBiomeException, with some biome information about the biome that caused the issue to develop.

**Closed as completed by TheWeatherPony** 2016-01-23 07:44 UTC
