### ISSUE TITLE
Dimension Bad local variable type Exception

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#79] opened 2016-01-20 22:14 UTC
Version: beta12b
AbyssalCraft Crash: http://pastebin.com/WPNAHqfn
TheBetweenlands: http://pastebin.com/Th8hJYBZ

There are some dimension mods that do not currently work at all with the seasons mod with Bad local variable type Exception error.  They just crash if you have them installed. I am sure there are more dimensional mods that will have this crash. I saw that dimensional testing needed to be done as a priority because, I saw it needed to be done and hasn't been tested in a couple months. I did this so seasons could work with other dimensions mods without just using only the overworld if people wanted to have mods. **Both abyssalcraft and the betweenlands crashed upon launcher from the seasons mod.**

**Comment by TheWeatherPony** [comment] 2016-01-20 22:22
Duplicate of #61, but involving different mods.

**Closed as completed by TheWeatherPony** 2016-01-20 22:22 UTC
Labels: duplicate

**Comment by jredfox** [comment] 2016-01-20 22:30
ok
