### ISSUE TITLE
Snow Doesn't Melt In Extreme Hills At Spring

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#70] opened 2016-01-11 02:42 UTC
Version: beta10
Images: http://imgur.com/v1u7Tve

Snow didn't melt at all in extreme hill type biomes in ten minuets.  I tested this on a 3x25 snow and ice sheet.  Not one tile or ice melted.

**Comment by TheWeatherPony** [comment] 2016-01-11 05:14
duplicate of #71

**Closed as completed by TheWeatherPony** 2016-01-11 05:14 UTC
Labels: duplicate
