### ISSUE TITLE
Snow Doesn't Melt In Cold Biomes At All= Snow Piling High To The Mountains 

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#74] opened 2016-01-11 04:05 UTC
Version: beta10

snow doesn't melt at all in cold biomes which will cause issues if you actually play the mod and snow will pile high to the mountains. So make a block limit or make it so it melts in cold biomes somehow slowly. You could even do something similar to the snowfall mod decay snow (melt) during winter until a specified layer which would be configurable. The current slopy snow falling mess messes up the vanilla ai of mobs. They just start spining in circles as if they don't know what to do who they are where they are going and where they are. If you smooth out the snow it should fix this issue of ai of mobs. See snowfall mod video. I like the snowfall mods properties on how you walk through snow sinking not on top. Could you add that with some items in the future once you get seasons working after it's 3.0 release? https://www.youtube.com/watch?v=UXK6Ae2Attg

**Comment by TheWeatherPony** [comment] 2016-01-11 07:06
The snow setting "tileLayerM" is the maximum height in snow tiles that snow tiles will stack from normal conditions.
Additionally, snow melting is controlled via temperature, which is customizable in the next build. #71

Snow is a work-in-progress, and is not finished being overhauled. see #67 ; duplicate of #35

**Closed as completed by TheWeatherPony** 2016-01-11 07:06 UTC

**Comment by jredfox** [comment] 2016-01-11 21:29
ok I just wanted to say that I think it should decay such as snowfall mod to a certain layer regardless of temperature and seasons like it does in real life to an extent. It does melt snow in winter but slowly and usually melts the most when the sun is out. So just make it slowly decay for cold biomes if you can make a Customizable  snow decay regardless of temperature specifically for cold biomes. However may as well do it globally and add this to your checklist of things to do.  If you don't like that idea then make something work with temperature and snow decaying to a certain y level in winter and or eventually melt
