### ISSUE TITLE
Exception ticking world

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#12] opened 2015-10-22 00:04 UTC
Exception ticking world
version: beta8b beta8c3
http://pastebin.com/5QRGRCLp

**Comment by TheWeatherPony** [comment] 2015-10-22 02:14
Duplicate of https://github.com/TheWeatherPony/ProjectPrivateRainbow/issues/8

**Closed as completed by TheWeatherPony** 2015-10-22 02:14 UTC
Labels: duplicate
