### ISSUE TITLE
java.lang.IllegalStateException: Already tesselating!

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#13] opened 2015-10-22 00:07 UTC
version: beta8b and beta8c3?
http://pastebin.com/zHRt2ZNN

**Comment by TheWeatherPony** [comment] 2015-10-22 01:09
Your trace only shows half of a problem, and doesn't link the cause on either end to anything I cause. My code shows up in the trace only because it has to in order for the rest of the code to run with my changes - my changes are not causing this to happen in what you have shown.

I am leaving this open in case you can get any other traces for this that might link back to my code more than circumstantially.

**Comment by jredfox** [comment] 2015-10-22 03:36
if this is a closed issue why is it in the open issues?

**Comment by TheWeatherPony** [comment] 2015-10-22 04:03
The closed issue is a duplicate of this one, which I closed and locked because it is a duplicate. 

I am leaving this open in case you can get any other traces for this that might link back to my code more than circumstantially.

**Comment by jredfox** [comment] 2015-10-22 04:13
I can't seem to recreate these. these occurred randomly and I think it's the performance / the launcher running it with ticks or something technical that I probably just made something completely up and it's different because, I am always run about theories

**Closed as completed** 2015-10-22 04:42 UTC
Labels: invalid
