### ISSUE TITLE
UponCreatingWorldAndSpawning@hotbiome

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#17] opened 2015-10-22 00:36 UTC
http://imgur.com/U1aoBnA
This occurs on hot biomes with no foliage . if you spawn in a jungle biome it doesn't crash . However if you spawn in a desert biome or mesa it crashes without optifine. 
1 http://pastebin.com/8JWutw6k
2 http://pastebin.com/5vgdbur3
3 http://pastebin.com/1riUENqt
4 http://pastebin.com/Xvj0UMA0 (mesa agian I think this is a duplicate)

**Comment by jredfox** [comment] 2015-10-22 00:47
I cannot paste anything else in the pastebin for 24 more hours so, I guess I will finish doing this tomorrow.

**Comment by PitchBright** [comment] 2015-10-22 01:29
Please provide screencapture of your seasons.dat file and show your hot biome settings.

**Comment by jredfox** [comment] 2015-10-22 01:31
Say what? I showed a video of this and it crashing. seasons.dat ok I can do that after it crashes if I can find that. Hot biome settings are vanilla. hold on

**Comment by jredfox** [comment] 2015-10-22 01:31
mesa
-840222844129379185
desert
-2341356369372073713

**Comment by jredfox** [comment] 2015-10-22 01:38
this contains seasons.dat also was glitching out my windows so all 4.dats should be in the world in the zip
http://www.mediafire.com/download/oze1au0i7kax7zm/Hot.zip

**Comment by PitchBright** [comment] 2015-10-22 01:40
Here's what you do: http://imgur.com/2wNn0lO

**Comment by jredfox** [comment] 2015-10-22 01:42
I didn't know why you wanted that file. ok get nbt and show it to imgur.com. do you still need it or did you take it from nbt editor and that's the image you shared with me?

**Comment by jredfox** [comment] 2015-10-22 01:43
ok so you want me to take a picture of the nbt hot biome settings got it sorry.

**Comment by jredfox** [comment] 2015-10-22 01:47
Here is the hot biome settings
http://imgur.com/U1aoBnA

**Comment by TheWeatherPony** [comment] 2015-10-22 02:39
Duplicate of #8, but with more details provided here.

**Closed as completed by TheWeatherPony** 2015-10-22 02:39 UTC
Labels: duplicate
